name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: saidacovrk.de
          username: ${{ Saida }}
          password: ${{ password }}
          server-dir: /saidacovrk.de/httpdocs/build/
          local-dir: ./build/
